Add support for CVSSv4
RedHatProductSecurity/cvss pull request #45
Opened 2023-12-08 15:29 UTC by jobiewinserapck

-Added class CVSS4
-Based the CVSS4 class on the js implementation found here: https://github.com/RedHatProductSecurity/cvss-v4-calculator -Added new tests for CVSS4
-Added new constants and exceptions for CVSS4
-Added json schema for CVSS4

2023-12-08 16:09 UTC, skontar commented
This looks really good. Thank you!

2023-12-08 16:12 UTC, skontar commented
@jobiewinserapck I presume you used the js implementation to generate test vectors?

2023-12-08 16:52 UTC, jobiewinserapck commented
Yes, I generated the vectors using the js implementation. I could Maybe get some screenshots tomorrow of how I did so. If thats helpful

2023-12-08 20:32 UTC, skontar commented
@jobiewinserapck can you rebase with master? I think that should re-run the CI with latest setup.

2023-12-10 00:51 UTC, jobiewinserapck commented
Sure thing I'll do that ASAP tomorrow morning

2023-12-11 10:17 UTC, skontar requested changes

2023-12-11 10:17 UTC, skontar commented on cvss/cvss4.py
> +            (str): cleaned CVSS3 with metrics in correct order
Should be 4.

2023-12-11 10:17 UTC, skontar commented on cvss/cvss4.py
> +            prefix = "CVSS:4/"
CVSS:4.0?

2023-12-11 10:17 UTC, skontar commented on cvss/cvss4.py
> +            CVSS3MandatoryError: if mandatory metric is missing in the vector
CVSS4MandatoryError

2023-12-11 10:17 UTC, skontar commented on cvss/cvss4.py
> +        Checks if mandatory fields are in CVSS3 vector.
CVSS4

2023-12-11 10:17 UTC, skontar commented on cvss/cvss4.py
> +        try:
Similarly as on 3, insert between 155 and 156:
```python
        # Handle 'CVSS:4.x' in the beginning of vector and split vector
        if not self.vector.startswith('CVSS:4.0/'):
            raise CVSS4MalformedError('Malformed CVSS4 vector "{0}" is missing mandatory prefix '
                                      'or uses unsupported CVSS version'.format(self.vector))
```

2023-12-11 10:17 UTC, skontar commented
@mprpic can you please review?

2023-12-11 13:25 UTC, jobiewinserapck commented
I'ved added those improvements, thanks for that @skontar!

2023-12-11 15:27 UTC, marco-silva0000 commented
just commenting for support, gogogo

2023-12-11 15:37 UTC, skontar approved these changes

2023-12-14 13:04 UTC, mprpic reviewed
Can you also please add import statements into the `cvss/__init__.py` file?

```
from .cvss4 import CVSS4
from .exceptions import CVSS4Error
```

2023-12-14 17:17 UTC, jobiewinserapck commented
I've pushed up a commit addressing the issues raised by @mprpic.

I also added some additional tests for malformed cvss strings

2023-12-17 20:42 UTC, skontar commented
@mprpic please re-review.

2023-12-18 07:23 UTC, mprpic approved these changes
LGTM!

2023-12-18 07:25 UTC, merged

2024-02-06 17:13 UTC, AdrianVollmer commented
I don't think `round_away_from_zero` is correct:

```console
$ python << EOF
from decimal import ROUND_HALF_UP
from decimal import Decimal as D
def round_away_from_zero(x, dp=1):
    return float(D(x).quantize(D("0." + "0" * dp), rounding=ROUND_HALF_UP))

for i in range(6):
    print(round_away_from_zero(i + 0.05))
EOF
0.1
1.1
2.0
3.0
4.0
5.0
```

It's inconsistent.

I would have said we should just do `round(x*10)/10` like the JavaScript implementation, but `Math.round(0.5)` is 1 in JS and `round(0.5)` is 0 in Python3 and 1 in Python2.  Python3 follows [IEEE 754](https://en.wikipedia.org/w/index.php?title=IEEE_754#Rounding_rules).

The specification document is not clear on which rounding convention should be used:

>     This score is rounded to one decimal place.

2024-02-06 18:55 UTC, skontar commented
Correct `.quantize` call should be able to resolve that difference. I do not recall what we did for v3.1 but we were able to get exactly the same results between Python and Javascript.

2024-02-06 19:45 UTC, skontar commented
@AdrianVollmer if the input is `Decimal` then `round_away_from_zero` works correctly I think.
```
>>> float((D(2) + D(5) / D(100)).quantize(D("0.0"), rounding=ROUND_HALF_UP))
2.1
```

2024-02-06 19:55 UTC, AdrianVollmer commented
Okay, but this function is only used once here and is passed a float:

https://github.com/RedHatProductSecurity/cvss/blob/c5dd7e2f0bcda1b32d509cce59a6db7c94bbec64/cvss/cvss4.py#L558

2024-02-07 07:59 UTC, AdrianVollmer commented
I think this function will suit this particular use case:

```python
def round_away_from_zero(value):
    # Only works correctly for positive values
    return int(value * 10 + 0.5) / 10.0
```

Since we only need to round values between 0.0 and 10.0, it should be fine.

```console
$ python << EOF
for i in range(10):
 print(int((i+0.05)*10 + 0.5)/10)
EOF
0.1
1.1
2.1
3.1
4.1
5.1
6.1
7.1
8.1
9.1
```