Fixes interactive mode for cvss v4.0
RedHatProductSecurity/cvss pull request #54
Opened 2024-04-03 02:45 UTC by chrisdlangton

addresses #47

2024-04-03 02:49 UTC, chrisdlangton commented
FYI
No tests existed for interactive mode, for me to update.
Searched for imports using `repo:RedHatProductSecurity/cvss path:/^tests\// interactive`

2024-04-03 10:52 UTC, jsvob requested changes
The calculator doesn't return a CVSS v4.0 score in either non-interactive and interactive mode.

```
$ cvss_calculator -4 -v "CVSS:4.0/AV:P/AC:H/AT:P/PR:H/UI:A/VC:L/VI:L/VA:L/SC:L/SI:L/SA:L/S:N"
Traceback (most recent call last):
  File "/TMP/cvss/venv/bin/cvss_calculator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/TMP/cvss/venv/lib64/python3.11/site-packages/cvss/cvss_calculator.py", line 63, in main
    scores = cvss_vector.scores()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'CVSS4' object has no attribute 'scores'

```

2024-04-03 12:03 UTC, chrisdlangton commented
![image](https://github.com/RedHatProductSecurity/cvss/assets/3494633/7ab2ca8d-fbfd-449b-9e0d-bbb9c0b0708d)
Should be working now, CVSS4 methods weren't API backwards compatible

2024-04-04 08:13 UTC, jsvob approved these changes
LGTM with a minor nitpick. Thank you!

2024-04-04 08:13 UTC, jsvob commented on cvss/cvss4.py
> +        Example: 6.5/CVSS:3.0/AV:P/AC:H/PR:H/UI:R/S:C/C:H/I:H/A:N/E:H/RL:O/RC:R/CR:H/MAC:H/MC:L
```suggestion
        Example: 7.3/CVSS:4.0/AV:P/AC:H/AT:N/PR:H/UI:P/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H/E:A
```

2024-04-04 10:24 UTC, merged